apiVersion: v2
name: eck-custom-resources-operator
description: Helm chart for eck-custom-resources operator
home: https://github.com/nosmicek/eck-custom-resources
sources:
  - https://github.com/nosmicek/eck-custom-resources
maintainers:
  - name: nosmicek
    url: https://github.com/nosmicek
type: application
version: 0.9.0
appVersion: 0.9.0
